// Playlist catalog — organized by PLATFORM
// Each platform (Pluto TV, Samsung TV Plus, LG Channels, Tubi, Roku, etc.)
// is a Provider with sub-playlists grouped under categories like
// "By Country" or "All Channels". Channel-type filtering (Sports/News/Movies/etc.)
// happens in the sidebar via the M3U group-title field, not at the provider level.

export type PlaylistItem = {
  id: string
  name: string
  flag?: string
  url: string
  /** Channel count hint shown in UI */
  count?: number
}

export type ProviderCategory = {
  id: string
  name: string
  flag?: string
  /** If set, clicking this category loads this URL directly (no sub-playlist picker) */
  directUrl?: string
  /** If set, this category contains multiple sub-playlists to pick from */
  playlists?: PlaylistItem[]
}

export type Provider = {
  id: string
  name: string
  description: string
  flag: string
  /** Real logo URL (shown in provider tab instead of emoji) */
  logo?: string
  categories: ProviderCategory[]
}

export const PROVIDERS: Provider[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // Best of FreeStream — curated top 100 channels per genre, all verified working
  // Generated by scripts/curate_best_100.py — re-run to refresh.
  // Every channel here has been tested (HLS manifest + .ts segment check) and
  // confirmed working as of the last run. 810 total curated channels.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'best-of',
    name: 'Best of FreeStream',
    description: 'Curated top channels per genre — all verified working',
    flag: '🏆',
    categories: [
      { id: 'sports', name: '⚽ Sports (97✓)', flag: '🏆', directUrl: '/curated/sports.m3u' },
      { id: 'movies', name: '🎬 Movies (176✓)', flag: '🏆', directUrl: '/curated/movies.m3u' },
      { id: 'news', name: 'News (100✓)', flag: '📰', directUrl: '/curated/news.m3u' },
      { id: 'music', name: 'Music (100✓)', flag: '🎵', directUrl: '/curated/music.m3u' },
      { id: 'kids', name: 'Kids (100✓)', flag: '👶', directUrl: '/curated/kids.m3u' },
      { id: 'entertainment', name: 'Entertainment (100✓)', flag: '🎪', directUrl: '/curated/entertainment.m3u' },
      { id: 'documentary', name: 'Documentary (100✓)', flag: '🔬', directUrl: '/curated/documentary.m3u' },
      { id: 'international', name: 'International (77✓)', flag: '🌍', directUrl: '/curated/international.m3u' },
      { id: 'religious', name: 'Religious (24✓)', flag: '🕌', directUrl: '/curated/religious.m3u' },
      { id: 'education', name: 'Education (9✓)', flag: '🎓', directUrl: '/curated/education.m3u' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Sports by Category — subcategories within sports
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'sports-cats',
    name: 'Sports by Category',
    description: 'Sports channels broken down by type — Football, Soccer, Basketball & more',
    flag: '🏅',
    categories: [
      {
        id: 'all-sports',
        name: 'All Sports (97✓)',
        flag: '🏆',
        directUrl: '/curated/sports.m3u',
      },
      {
        id: 'subcats',
        name: 'By Sport Type',
        flag: '📂',
        playlists: [
          { id: 'football', name: '🏈 Football (18✓)', flag: '🏈', url: '/curated/sports-football.m3u' },
          { id: 'soccer', name: '⚽ Soccer (20✓)', flag: '⚽', url: '/curated/sports-soccer.m3u' },
          { id: 'basketball', name: '🏀 Basketball (3✓)', flag: '🏀', url: '/curated/sports-basketball.m3u' },
          { id: 'baseball', name: '⚾ Baseball (2✓)', flag: '⚾', url: '/curated/sports-baseball.m3u' },
          { id: 'hockey', name: '🏒 Hockey (1✓)', flag: '🏒', url: '/curated/sports-hockey.m3u' },
          { id: 'combat', name: '🥊 Combat (20✓)', flag: '🥊', url: '/curated/sports-combat.m3u' },
          { id: 'racing', name: '🏎️ Racing (10✓)', flag: '🏎️', url: '/curated/sports-racing.m3u' },
          { id: 'college', name: '🎓 College (3✓)', flag: '🎓', url: '/curated/sports-college.m3u' },
          { id: 'general', name: '🏆 General Sports (20✓)', flag: '🏆', url: '/curated/sports-general-sports.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Movies by Category — subcategories within movies
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'movies-cats',
    name: 'Movies by Category',
    description: 'Movie channels broken down by genre — Action, Comedy, Drama & more',
    flag: '🎞️',
    categories: [
      {
        id: 'all-movies',
        name: 'All Movies (176✓)',
        flag: '🎬',
        directUrl: '/curated/movies.m3u',
      },
      {
        id: 'subcats',
        name: 'By Movie Genre',
        flag: '📂',
        playlists: [
          { id: 'action', name: '💥 Action (22✓)', flag: '💥', url: '/curated/movies-action.m3u' },
          { id: 'comedy', name: '😂 Comedy (22✓)', flag: '😂', url: '/curated/movies-comedy.m3u' },
          { id: 'drama', name: '🎭 Drama (22✓)', flag: '🎭', url: '/curated/movies-drama.m3u' },
          { id: 'horror', name: '👻 Horror (22✓)', flag: '👻', url: '/curated/movies-horror.m3u' },
          { id: 'classic', name: '📽️ Classic (22✓)', flag: '📽️', url: '/curated/movies-classic.m3u' },
          { id: 'western', name: '🤠 Western (22✓)', flag: '🤠', url: '/curated/movies-western.m3u' },
          { id: 'scifi', name: '🚀 Sci-Fi & Fantasy (22✓)', flag: '🚀', url: '/curated/movies-scifi.m3u' },
          { id: 'general', name: '🎬 General Movies (22✓)', flag: '🎬', url: '/curated/movies-general-movies.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Countries — channels aggregated by country across ALL providers
  // Generated by scripts/aggregate_countries.py — 48 countries, 781 channels
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'countries',
    name: 'Countries',
    description: 'Channels by country — aggregated across all providers',
    flag: '🌍',
    categories: [
      {
        id: 'all-countries',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'it', name: 'Italy (100)', flag: '🇮🇹', url: '/countries/it.m3u' },
          { id: 'id', name: 'Indonesia (92)', flag: '🇮🇩', url: '/countries/id.m3u' },
          { id: 'us', name: 'United States (74)', flag: '🇺🇸', url: '/countries/us.m3u' },
          { id: 'es', name: 'Spain (48)', flag: '🇪🇸', url: '/countries/es.m3u' },
          { id: 'gr', name: 'Greece (42)', flag: '🇬🇷', url: '/countries/gr.m3u' },
          { id: 'cz', name: 'Czech Republic (34)', flag: '🇨🇿', url: '/countries/cz.m3u' },
          { id: 'ru', name: 'Russia (33)', flag: '🇷🇺', url: '/countries/ru.m3u' },
          { id: 'in', name: 'India (33)', flag: '🇮🇳', url: '/countries/in.m3u' },
          { id: 'fr', name: 'France (26)', flag: '🇫🇷', url: '/countries/fr.m3u' },
          { id: 'gb', name: 'United Kingdom (24)', flag: '🇬🇧', url: '/countries/gb.m3u' },
          { id: 'de', name: 'Germany (24)', flag: '🇩🇪', url: '/countries/de.m3u' },
          { id: 'ar', name: 'Argentina (21)', flag: '🇦🇷', url: '/countries/ar.m3u' },
          { id: 'kr', name: 'South Korea (21)', flag: '🇰🇷', url: '/countries/kr.m3u' },
          { id: 'ua', name: 'Ukraine (20)', flag: '🇺🇦', url: '/countries/ua.m3u' },
          { id: 'fi', name: 'Finland (19)', flag: '🇫🇮', url: '/countries/fi.m3u' },
          { id: 'hu', name: 'Hungary (15)', flag: '🇭🇺', url: '/countries/hu.m3u' },
          { id: 'tr', name: 'Turkey (14)', flag: '🇹🇷', url: '/countries/tr.m3u' },
          { id: 'nl', name: 'Netherlands (11)', flag: '🇳🇱', url: '/countries/nl.m3u' },
          { id: 'br', name: 'Brazil (10)', flag: '🇧🇷', url: '/countries/br.m3u' },
          { id: 'cl', name: 'Chile (10)', flag: '🇨🇱', url: '/countries/cl.m3u' },
          { id: 'qa', name: 'Qatar (10)', flag: '🇶🇦', url: '/countries/qa.m3u' },
          { id: 'ie', name: 'Ireland (9)', flag: '🇮🇪', url: '/countries/ie.m3u' },
          { id: 'ir', name: 'Iran (8)', flag: '🇮🇷', url: '/countries/ir.m3u' },
          { id: 'sa', name: 'Saudi Arabia (8)', flag: '🇸🇦', url: '/countries/sa.m3u' },
          { id: 'tw', name: 'Taiwan (8)', flag: '🇹🇼', url: '/countries/tw.m3u' },
          { id: 'eg', name: 'Egypt (7)', flag: '🇪🇬', url: '/countries/eg.m3u' },
          { id: 'iq', name: 'Iraq (7)', flag: '🇮🇶', url: '/countries/iq.m3u' },
          { id: 'ca', name: 'Canada (6)', flag: '🇨🇦', url: '/countries/ca.m3u' },
          { id: 'se', name: 'Sweden (5)', flag: '🇸🇪', url: '/countries/se.m3u' },
          { id: 'ae', name: 'UAE (5)', flag: '🇦🇪', url: '/countries/ae.m3u' },
          { id: 'cn', name: 'China (4)', flag: '🇨🇳', url: '/countries/cn.m3u' },
          { id: 'au', name: 'Australia (3)', flag: '🇦🇺', url: '/countries/au.m3u' },
          { id: 'jp', name: 'Japan (3)', flag: '🇯🇵', url: '/countries/jp.m3u' },
          { id: 'ke', name: 'Kenya (3)', flag: '🇰🇪', url: '/countries/ke.m3u' },
          { id: 'at', name: 'Austria (3)', flag: '🇦🇹', url: '/countries/at.m3u' },
          { id: 'hk', name: 'Hong Kong (3)', flag: '🇭🇰', url: '/countries/hk.m3u' },
          { id: 'dk', name: 'Denmark (2)', flag: '🇩🇰', url: '/countries/dk.m3u' },
          { id: 'il', name: 'Israel (2)', flag: '🇮🇱', url: '/countries/il.m3u' },
          { id: 'th', name: 'Thailand (2)', flag: '🇹🇭', url: '/countries/th.m3u' },
          { id: 'ng', name: 'Nigeria (2)', flag: '🇳🇬', url: '/countries/ng.m3u' },
          { id: 'ch', name: 'Switzerland (2)', flag: '🇨🇭', url: '/countries/ch.m3u' },
          { id: 'ro', name: 'Romania (2)', flag: '🇷🇴', url: '/countries/ro.m3u' },
          { id: 'no', name: 'Norway (1)', flag: '🇳🇴', url: '/countries/no.m3u' },
          { id: 'pl', name: 'Poland (1)', flag: '🇵🇱', url: '/countries/pl.m3u' },
          { id: 'my', name: 'Malaysia (1)', flag: '🇲🇾', url: '/countries/my.m3u' },
          { id: 'gh', name: 'Ghana (1)', flag: '🇬🇭', url: '/countries/gh.m3u' },
          { id: 'pt', name: 'Portugal (1)', flag: '🇵🇹', url: '/countries/pt.m3u' },
          { id: 'be', name: 'Belgium (1)', flag: '🇧🇪', url: '/countries/be.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Leagues — channels classified by football leagues & sports championships
  // Generated by scripts/classify_leagues.py — 170 verified working channels
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'leagues',
    name: 'Leagues & Championships',
    description: 'Channels by league — Premier League, La Liga, World Cup & more',
    flag: '🏆',
    categories: [
      {
        id: 'all-leagues',
        name: 'By League',
        flag: '🏆',
        playlists: [
          { id: 'premier-league', name: '🦁 Premier League (16✓)', flag: '🦁', url: '/leagues/premier-league.m3u' },
          { id: 'la-liga', name: '🇪🇸 La Liga (5✓)', flag: '🇪🇸', url: '/leagues/la-liga.m3u' },
          { id: 'champions-league', name: '🏆 Champions League (4✓)', flag: '🏆', url: '/leagues/champions-league.m3u' },
          { id: 'europa-league', name: '🥈 Europa League (5✓)', flag: '🥈', url: '/leagues/europa-league.m3u' },
          { id: 'world-cup-2026', name: '🏆 World Cup 2026 (50✓)', flag: '🏆', url: '/leagues/world-cup-2026.m3u' },
          { id: 'other-football', name: '⚽ Other Football (50✓)', flag: '⚽', url: '/leagues/other-football.m3u' },
          { id: 'nfl', name: '🏈 NFL (6✓)', flag: '🏈', url: '/leagues/nfl.m3u' },
          { id: 'nba', name: '🏀 NBA (2✓)', flag: '🏀', url: '/leagues/nba.m3u' },
          { id: 'mlb', name: '⚾ MLB (4✓)', flag: '⚾', url: '/leagues/mlb.m3u' },
          { id: 'nhl', name: '🏒 NHL (2✓)', flag: '🏒', url: '/leagues/nhl.m3u' },
          { id: 'ufc-mma', name: '🥊 UFC & MMA (30✓)', flag: '🥊', url: '/leagues/ufc-mma.m3u' },
          { id: 'f1-racing', name: '🏎️ F1 & Motorsport (7✓)', flag: '🏎️', url: '/leagues/f1-racing.m3u' },
          { id: 'college-sports', name: '🎓 College NCAA (2✓)', flag: '🎓', url: '/leagues/college-sports.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // World Regions — channels grouped by world region (aggregated from countries)
  // Generated by scripts/aggregate_regions.py — 767 channels across 8 regions
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'world-regions',
    name: 'World Regions',
    description: 'Channels by world region — Europe, Asia, Americas & more',
    flag: '🗺️',
    categories: [
      {
        id: 'all-regions',
        name: 'By Region',
        flag: '🗺️',
        playlists: [
          { id: 'europe', name: '🇪🇺 Europe (423)', flag: '🇪🇺', url: '/regions/europe.m3u' },
          { id: 'east-southeast-asia', name: '🌏 East & SE Asia (134)', flag: '🌏', url: '/regions/east-southeast-asia.m3u' },
          { id: 'north-america', name: '🌎 North America (80)', flag: '🌎', url: '/regions/north-america.m3u' },
          { id: 'south-central-america', name: '🌴 South & Central America (41)', flag: '🌴', url: '/regions/south-central-america.m3u' },
          { id: 'middle-east-north-africa', name: '🕌 Middle East & North Africa (47)', flag: '🕌', url: '/regions/middle-east-north-africa.m3u' },
          { id: 'south-asia', name: '🇮🇳 South Asia (33)', flag: '🇮🇳', url: '/regions/south-asia.m3u' },
          { id: 'sub-saharan-africa', name: '🌍 Sub-Saharan Africa (6)', flag: '🌍', url: '/regions/sub-saharan-africa.m3u' },
          { id: 'oceania', name: '🇦🇺 Oceania (3)', flag: '🇦🇺', url: '/regions/oceania.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Pluto TV — via iptv-org/iptv/streams/
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'pluto-tv',
    name: 'Pluto TV',
    description: 'Free ad-supported TV by Paramount — 12 countries',
    flag: '🆓',
    logo: '/logos/pluto-tv.svg',
    categories: [
      {
        id: 'by-country',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'us', name: 'USA', flag: '🇺🇸', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_pluto.m3u', count: 410 },
          { id: 'uk', name: 'UK', flag: '🇬🇧', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/uk_pluto.m3u', count: 192 },
          { id: 'at', name: 'Austria', flag: '🇦🇹', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/at_pluto.m3u' },
          { id: 'br', name: 'Brazil', flag: '🇧🇷', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/br_pluto.m3u' },
          { id: 'ca', name: 'Canada', flag: '🇨🇦', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ca_pluto.m3u' },
          { id: 'ch', name: 'Switzerland', flag: '🇨🇭', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ch_pluto.m3u' },
          { id: 'de', name: 'Germany', flag: '🇩🇪', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/de_pluto.m3u', count: 195 },
          { id: 'dk', name: 'Denmark', flag: '🇩🇰', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/dk_pluto.m3u' },
          { id: 'es', name: 'Spain', flag: '🇪🇸', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/es_pluto.m3u', count: 144 },
          { id: 'fr', name: 'France', flag: '🇫🇷', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fr_pluto.m3u', count: 134 },
          { id: 'it', name: 'Italy', flag: '🇮🇹', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/it_pluto.m3u' },
          { id: 'se', name: 'Sweden', flag: '🇸🇪', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/se_pluto.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Samsung TV Plus — via iptv-org/iptv/streams/ (filtered)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'samsung-tv',
    name: 'Samsung TV Plus',
    description: 'Free TV by Samsung — 15 countries (filtered)',
    flag: '📱',
    logo: '/logos/samsung-tv.svg',
    categories: [
      {
        id: 'by-country',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'us', name: 'USA (252✓)', flag: '🇺🇸', url: '/filtered/iptv-streams-samsung-tv-us-samsung.m3u', count: 252 },
          { id: 'uk', name: 'UK (120✓)', flag: '🇬🇧', url: '/filtered/iptv-streams-samsung-tv-uk-samsung.m3u', count: 120 },
          { id: 'de', name: 'Germany (1✓)', flag: '🇩🇪', url: '/filtered/iptv-streams-samsung-tv-de-samsung.m3u', count: 1 },
          { id: 'at', name: 'Austria', flag: '🇦🇹', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/at_samsung.m3u' },
          { id: 'au', name: 'Australia', flag: '🇦🇺', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/au_samsung.m3u' },
          { id: 'be', name: 'Belgium', flag: '🇧🇪', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/be_samsung.m3u' },
          { id: 'br', name: 'Brazil', flag: '🇧🇷', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/br_samsung.m3u' },
          { id: 'ca', name: 'Canada', flag: '🇨🇦', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ca_samsung.m3u' },
          { id: 'ch', name: 'Switzerland', flag: '🇨🇭', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ch_samsung.m3u' },
          { id: 'dk', name: 'Denmark', flag: '🇩🇰', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/dk_samsung.m3u' },
          { id: 'es', name: 'Spain', flag: '🇪🇸', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/es_samsung.m3u' },
          { id: 'fi', name: 'Finland', flag: '🇫🇮', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fi_samsung.m3u' },
          { id: 'fr', name: 'France', flag: '🇫🇷', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fr_samsung.m3u' },
          { id: 'it', name: 'Italy', flag: '🇮🇹', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/it_samsung.m3u' },
          { id: 'se', name: 'Sweden', flag: '🇸🇪', url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/se_samsung.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LG Channels — via apsattv.com (32 countries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'lg-channels',
    name: 'LG Channels',
    description: 'Free TV by LG Electronics — 32 countries',
    flag: '📺',
    logo: '/logos/lg-channels.svg',
    categories: [
      {
        id: 'by-country',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'us', name: 'USA (445)', flag: '🇺🇸', url: 'https://www.apsattv.com/uslg.m3u', count: 445 },
          { id: 'gb', name: 'UK (300)', flag: '🇬🇧', url: 'https://www.apsattv.com/gblg.m3u', count: 300 },
          { id: 'de', name: 'Germany (210)', flag: '🇩🇪', url: 'https://www.apsattv.com/delg.m3u', count: 210 },
          { id: 'fr', name: 'France (182)', flag: '🇫🇷', url: 'https://www.apsattv.com/frlg.m3u', count: 182 },
          { id: 'es', name: 'Spain', flag: '🇪🇸', url: 'https://www.apsattv.com/eslg.m3u' },
          { id: 'it', name: 'Italy', flag: '🇮🇹', url: 'https://www.apsattv.com/itlg.m3u' },
          { id: 'au', name: 'Australia', flag: '🇦🇺', url: 'https://www.apsattv.com/aulg.m3u' },
          { id: 'ca', name: 'Canada', flag: '🇨🇦', url: 'https://www.apsattv.com/calg.m3u' },
          { id: 'br', name: 'Brazil', flag: '🇧🇷', url: 'https://www.apsattv.com/brlg.m3u' },
          { id: 'mx', name: 'Mexico', flag: '🇲🇽', url: 'https://www.apsattv.com/mxlg.m3u' },
          { id: 'jp', name: 'Japan', flag: '🇯🇵', url: 'https://www.apsattv.com/jplg.m3u' },
          { id: 'kr', name: 'Korea', flag: '🇰🇷', url: 'https://www.apsattv.com/krlg.m3u' },
          { id: 'in', name: 'India', flag: '🇮🇳', url: 'https://www.apsattv.com/inlg.m3u' },
          { id: 'ae', name: 'UAE', flag: '🇦🇪', url: 'https://www.apsattv.com/aelg.m3u' },
          { id: 'ar', name: 'Argentina', flag: '🇦🇷', url: 'https://www.apsattv.com/arlg.m3u' },
          { id: 'cl', name: 'Chile', flag: '🇨🇱', url: 'https://www.apsattv.com/cllg.m3u' },
          { id: 'co', name: 'Colombia', flag: '🇨🇴', url: 'https://www.apsattv.com/colg.m3u' },
          { id: 'nl', name: 'Netherlands', flag: '🇳🇱', url: 'https://www.apsattv.com/nllg.m3u' },
          { id: 'se', name: 'Sweden', flag: '🇸🇪', url: 'https://www.apsattv.com/selg.m3u' },
          { id: 'no', name: 'Norway', flag: '🇳🇴', url: 'https://www.apsattv.com/nolg.m3u' },
          { id: 'dk', name: 'Denmark', flag: '🇩🇰', url: 'https://www.apsattv.com/dklg.m3u' },
          { id: 'fi', name: 'Finland', flag: '🇫🇮', url: 'https://www.apsattv.com/filg.m3u' },
          { id: 'pl', name: 'Poland', flag: '🇵🇱', url: 'https://www.apsattv.com/pllg.m3u' },
          { id: 'pt', name: 'Portugal', flag: '🇵🇹', url: 'https://www.apsattv.com/ptlg.m3u' },
          { id: 'at', name: 'Austria', flag: '🇦🇹', url: 'https://www.apsattv.com/atlg.m3u' },
          { id: 'be', name: 'Belgium', flag: '🇧🇪', url: 'https://www.apsattv.com/belg.m3u' },
          { id: 'ch', name: 'Switzerland', flag: '🇨🇭', url: 'https://www.apsattv.com/chlg.m3u' },
          { id: 'ie', name: 'Ireland', flag: '🇮🇪', url: 'https://www.apsattv.com/ielg.m3u' },
          { id: 'lu', name: 'Luxembourg', flag: '🇱🇺', url: 'https://www.apsattv.com/lulg.m3u' },
          { id: 'nz', name: 'New Zealand', flag: '🇳🇿', url: 'https://www.apsattv.com/nzlg.m3u' },
          { id: 'pe', name: 'Peru', flag: '🇵🇪', url: 'https://www.apsattv.com/pelg.m3u' },
          { id: 'sg', name: 'Singapore', flag: '🇸🇬', url: 'https://www.apsattv.com/sglg.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Tubi TV — via BuddyChewChew GitHub
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'tubi',
    name: 'Tubi TV',
    description: 'Free ad-supported TV by Fox — 176 channels',
    flag: '🦊',
    logo: '/logos/tubi.png',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: 'https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/refs/heads/main/playlists/tubi_all.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Roku Channel — via BuddyChewChew GitHub
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'roku',
    name: 'Roku Channel',
    description: 'Free ad-supported TV by Roku — 352 channels',
    flag: '🔴',
    logo: '/logos/roku.png',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: 'https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/refs/heads/main/playlists/roku_all.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Vizio TV — via apsattv.com
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'vizio',
    name: 'Vizio WatchFree+',
    description: 'Free ad-supported TV by Vizio — 433 channels',
    flag: '📺',
    logo: '/logos/vizio.png',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: 'https://www.apsattv.com/vizio.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Xumo TV — via apsattv.com
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'xumo',
    name: 'Xumo TV',
    description: 'Free ad-supported TV by Xumo — 389 channels',
    flag: '📺',
    logo: '/logos/xumo.png',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: 'https://www.apsattv.com/xumo.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Rakuten TV — via apsattv.com
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'rakuten',
    name: 'Rakuten TV',
    description: 'Free ad-supported TV by Rakuten — UK & France',
    flag: '🇯🇵',
    logo: '/logos/rakuten.png',
    categories: [
      {
        id: 'by-country',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'uk', name: 'UK (169)', flag: '🇬🇧', url: 'https://www.apsattv.com/rakutentv-uk.m3u', count: 169 },
          { id: 'fr', name: 'France', flag: '🇫🇷', url: 'https://www.apsattv.com/rakutentv-fr.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Other FAST Platforms — via apsattv.com (single-playlist platforms)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'other-fast',
    name: 'More FAST',
    description: 'TCL, HP, LocalNow, Cineverse, Whale TV, Distro & more',
    flag: '📡',
    logo: '/logos/other-fast.svg',
    categories: [
      {
        id: 'all',
        name: 'All Platforms',
        flag: '📺',
        playlists: [
          { id: 'tcl', name: 'TCL TV Plus (494)', flag: '📺', url: 'https://www.apsattv.com/tclplus.m3u', count: 494 },
          { id: 'localnow', name: 'LocalNow (447)', flag: '🇺🇸', url: 'https://www.apsattv.com/localnow.m3u', count: 447 },
          { id: 'whale', name: 'Whale TV Plus (360)', flag: '🐋', url: 'https://www.apsattv.com/whaletvplus_all.m3u', count: 360 },
          { id: 'hp', name: 'HP Fast (134)', flag: '💻', url: 'https://www.apsattv.com/hp.m3u', count: 134 },
          { id: 'cineverse', name: 'Cineverse (30)', flag: '🎬', url: 'https://www.apsattv.com/cineverse.m3u', count: 30 },
          { id: 'vidaa', name: 'Vidaa TV', flag: '📺', url: 'https://www.apsattv.com/vidaa.m3u' },
          { id: 'orka', name: 'Orka TV', flag: '📺', url: 'https://www.apsattv.com/orka.m3u' },
          { id: 'kogan', name: 'Kogan TV Plus (AU)', flag: '🇦🇺', url: 'https://www.apsattv.com/kogantvplus.m3u' },
          { id: 'metax', name: 'Metax', flag: '📺', url: 'https://www.apsattv.com/metax.m3u' },
          { id: 'galxy', name: 'Galaxy.TV', flag: '📺', url: 'https://www.apsattv.com/galxytv.m3u' },
          { id: 'igocast', name: 'Igocast', flag: '📺', url: 'https://www.apsattv.com/igocast.m3u' },
          { id: 'rewarded', name: 'Rewarded TV', flag: '🎁', url: 'https://www.apsattv.com/rewardedtv.m3u' },
          { id: 'distro', name: 'Distro', flag: '📦', url: 'https://www.apsattv.com/distro.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // beIN Sports — verified working free streams
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'bein',
    name: 'beIN Sports',
    description: 'Verified working beIN streams — XTRA, XTRA Ñ, Haber',
    flag: '⚽',
    logo: '/logos/bein.png',
    categories: [
      {
        id: 'verified',
        name: 'Verified Working',
        flag: '✅',
        directUrl: '/filtered/bein-verified.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // FAST IPTV (ahan443) — Indonesian, Bangladeshi, Indian, World Cup 2026
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'fast-iptv',
    name: 'FAST IPTV',
    description: 'South Asian TV + World Cup 2026 — 744 verified working',
    flag: '⚡',
    categories: [
      {
        id: 'world-cup',
        name: 'World Cup 2026',
        flag: '🏆',
        playlists: [
          { id: 'fifa', name: 'FIFA BDIX (12✓)', flag: '⚽', url: '/filtered/fast-iptv-world-cup-f-fifa.m3u', count: 12 },
          { id: 'combined', name: 'Combined Sports (117✓)', flag: '🏅', url: '/filtered/fast-iptv-world-cup-f-combined.m3u', count: 117 },
        ],
      },
      {
        id: 'by-country',
        name: 'By Country',
        flag: '🗺️',
        playlists: [
          { id: 'indian', name: 'Indian (28✓)', flag: '🇮🇳', url: '/filtered/fast-iptv-countries-f-indian.m3u', count: 28 },
          { id: 'world-4k', name: 'Bangladesh 4K (60)', flag: '🇧🇩', url: 'https://raw.githubusercontent.com/ahan443/FAST-IPTV/main/m3u_world_4k.m3u8', count: 60 },
          { id: 'play', name: 'Indonesia Play (151✓)', flag: '🇮🇩', url: '/filtered/fast-iptv-countries-f-play.m3u', count: 151 },
        ],
      },
      {
        id: 'content',
        name: 'Movies & Shows',
        flag: '🎬',
        playlists: [
          { id: 'movies', name: 'Movies (78✓)', flag: '🎬', url: '/filtered/fast-iptv-content-f-movies.m3u', count: 78 },
          { id: 'animation', name: 'Animation (6)', flag: '🎨', url: 'https://raw.githubusercontent.com/ahan443/FAST-IPTV/main/animation.m3u' },
          { id: 'direct', name: 'Direct M3U (220✓)', flag: '📺', url: '/filtered/fast-iptv-content-f-direct.m3u', count: 220 },
          { id: 'channels', name: 'Channels (138✓)', flag: '📡', url: '/filtered/fast-iptv-content-f-channels.m3u', count: 138 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // IPTV4ON — user's uploaded local playlist (filtered: 165 working)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'iptv4on',
    name: 'IPTV4ON',
    description: 'Arabic, beIN, France, World Cup — verified working',
    flag: '🎬',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: '/filtered/iptv4on-all.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Free-TV — aggregated Pluto/Plex/Samsung (filtered: 731 working)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'free-tv',
    name: 'Free-TV Aggregated',
    description: 'Pluto + Plex + Samsung combined — 731 verified working',
    flag: '📺',
    categories: [
      {
        id: 'all',
        name: 'All Channels',
        flag: '📺',
        directUrl: '/filtered/free-tv-all.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // World IPTV (Romaxa55) — auto-verified every 6 hours
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'world-iptv',
    name: 'World IPTV',
    description: 'Auto-verified every 6 hours — 14,148 channels filtered to 261✓',
    flag: '✅',
    categories: [
      {
        id: 'verified',
        name: 'Verified (filtered)',
        flag: '🌐',
        directUrl: '/filtered/world-iptv-verified-all.m3u',
      },
      {
        id: 'full',
        name: 'Full Playlist',
        flag: '🌍',
        directUrl: 'https://romaxa55.github.io/world_ip_tv/output/index.m3u',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // IPTV-org — main public directory
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'iptv-org',
    name: 'IPTV-org',
    description: 'Main public IPTV directory — 8,000+ channels worldwide',
    flag: '🌍',
    logo: '/logos/iptv-org.png',
    categories: [
      {
        id: 'by-language',
        name: 'By Language',
        flag: '🗣️',
        playlists: [
          { id: 'ara', name: 'Arabic', flag: '🇸🇦', url: 'https://iptv-org.github.io/iptv/languages/ara.m3u' },
          { id: 'eng', name: 'English', flag: '🇬🇧', url: 'https://iptv-org.github.io/iptv/languages/eng.m3u' },
          { id: 'fra', name: 'French', flag: '🇫🇷', url: 'https://iptv-org.github.io/iptv/languages/fra.m3u' },
          { id: 'deu', name: 'German', flag: '🇩🇪', url: 'https://iptv-org.github.io/iptv/languages/deu.m3u' },
          { id: 'rus', name: 'Russian', flag: '🇷🇺', url: 'https://iptv-org.github.io/iptv/languages/rus.m3u' },
          { id: 'tur', name: 'Turkish', flag: '🇹🇷', url: 'https://iptv-org.github.io/iptv/languages/tur.m3u' },
          { id: 'hin', name: 'Hindi', flag: '🇮🇳', url: 'https://iptv-org.github.io/iptv/languages/hin.m3u' },
          { id: 'urd', name: 'Urdu', flag: '🇵🇰', url: 'https://iptv-org.github.io/iptv/languages/urd.m3u' },
          { id: 'zho', name: 'Chinese', flag: '🇨🇳', url: 'https://iptv-org.github.io/iptv/languages/zho.m3u' },
          { id: 'fas', name: 'Persian', flag: '🇮🇷', url: 'https://iptv-org.github.io/iptv/languages/per.m3u' },
          { id: 'heb', name: 'Hebrew', flag: '🇮🇱', url: 'https://iptv-org.github.io/iptv/languages/heb.m3u' },
          { id: 'spa', name: 'Spanish', flag: '🇪🇸', url: 'https://iptv-org.github.io/iptv/languages/spa.m3u' },
          { id: 'por', name: 'Portuguese', flag: '🇵🇹', url: 'https://iptv-org.github.io/iptv/languages/por.m3u' },
        ],
      },
      {
        id: 'arabic-countries',
        name: 'Arabic Countries',
        flag: '🇸🇦',
        playlists: [
          { id: 'eg', name: 'Egypt', flag: '🇪🇬', url: 'https://iptv-org.github.io/iptv/countries/eg.m3u' },
          { id: 'sa', name: 'Saudi Arabia', flag: '🇸🇦', url: 'https://iptv-org.github.io/iptv/countries/sa.m3u' },
          { id: 'ae', name: 'UAE', flag: '🇦🇪', url: 'https://iptv-org.github.io/iptv/countries/ae.m3u' },
          { id: 'qa', name: 'Qatar', flag: '🇶🇦', url: 'https://iptv-org.github.io/iptv/countries/qa.m3u' },
          { id: 'kw', name: 'Kuwait', flag: '🇰🇼', url: 'https://iptv-org.github.io/iptv/countries/kw.m3u' },
          { id: 'bh', name: 'Bahrain', flag: '🇧🇭', url: 'https://iptv-org.github.io/iptv/countries/bh.m3u' },
          { id: 'om', name: 'Oman', flag: '🇴🇲', url: 'https://iptv-org.github.io/iptv/countries/om.m3u' },
          { id: 'jo', name: 'Jordan', flag: '🇯🇴', url: 'https://iptv-org.github.io/iptv/countries/jo.m3u' },
          { id: 'lb', name: 'Lebanon', flag: '🇱🇧', url: 'https://iptv-org.github.io/iptv/countries/lb.m3u' },
          { id: 'sy', name: 'Syria', flag: '🇸🇾', url: 'https://iptv-org.github.io/iptv/countries/sy.m3u' },
          { id: 'iq', name: 'Iraq', flag: '🇮🇶', url: 'https://iptv-org.github.io/iptv/countries/iq.m3u' },
          { id: 'ps', name: 'Palestine', flag: '🇵🇸', url: 'https://iptv-org.github.io/iptv/countries/ps.m3u' },
          { id: 'tn', name: 'Tunisia', flag: '🇹🇳', url: 'https://iptv-org.github.io/iptv/countries/tn.m3u' },
          { id: 'dz', name: 'Algeria', flag: '🇩🇿', url: 'https://iptv-org.github.io/iptv/countries/dz.m3u' },
          { id: 'ma', name: 'Morocco', flag: '🇲🇦', url: 'https://iptv-org.github.io/iptv/countries/ma.m3u' },
        ],
      },
      {
        id: 'world-countries',
        name: 'World Countries',
        flag: '🗺️',
        playlists: [
          { id: 'us', name: 'USA', flag: '🇺🇸', url: 'https://iptv-org.github.io/iptv/countries/us.m3u' },
          { id: 'uk', name: 'UK', flag: '🇬🇧', url: 'https://iptv-org.github.io/iptv/countries/uk.m3u' },
          { id: 'fr', name: 'France', flag: '🇫🇷', url: 'https://iptv-org.github.io/iptv/countries/fr.m3u' },
          { id: 'de', name: 'Germany', flag: '🇩🇪', url: 'https://iptv-org.github.io/iptv/countries/de.m3u' },
          { id: 'tr', name: 'Turkey', flag: '🇹🇷', url: 'https://iptv-org.github.io/iptv/countries/tr.m3u' },
          { id: 'ir', name: 'Iran', flag: '🇮🇷', url: 'https://iptv-org.github.io/iptv/countries/ir.m3u' },
          { id: 'in', name: 'India', flag: '🇮🇳', url: 'https://iptv-org.github.io/iptv/countries/in.m3u' },
          { id: 'cn', name: 'China', flag: '🇨🇳', url: 'https://iptv-org.github.io/iptv/countries/cn.m3u' },
          { id: 'jp', name: 'Japan', flag: '🇯🇵', url: 'https://iptv-org.github.io/iptv/countries/jp.m3u' },
          { id: 'kr', name: 'Korea', flag: '🇰🇷', url: 'https://iptv-org.github.io/iptv/countries/kr.m3u' },
          { id: 'br', name: 'Brazil', flag: '🇧🇷', url: 'https://iptv-org.github.io/iptv/countries/br.m3u' },
          { id: 'ru', name: 'Russia', flag: '🇷🇺', url: 'https://iptv-org.github.io/iptv/countries/ru.m3u' },
        ],
      },
      {
        id: 'by-genre',
        name: 'By Genre',
        flag: '🎬',
        playlists: [
          { id: 'sports', name: 'Sports', flag: '⚽', url: 'https://iptv-org.github.io/iptv/categories/sports.m3u' },
          { id: 'news', name: 'News', flag: '📰', url: 'https://iptv-org.github.io/iptv/categories/news.m3u' },
          { id: 'movies', name: 'Movies', flag: '🎬', url: 'https://iptv-org.github.io/iptv/categories/movies.m3u' },
          { id: 'music', name: 'Music', flag: '🎵', url: 'https://iptv-org.github.io/iptv/categories/music.m3u' },
          { id: 'kids', name: 'Kids', flag: '👶', url: 'https://iptv-org.github.io/iptv/categories/kids.m3u' },
          { id: 'entertainment', name: 'Entertainment', flag: '🎪', url: 'https://iptv-org.github.io/iptv/categories/entertainment.m3u' },
          { id: 'documentary', name: 'Documentary', flag: '🔬', url: 'https://iptv-org.github.io/iptv/categories/documentary.m3u' },
          { id: 'religious', name: 'Religious', flag: '🕌', url: 'https://iptv-org.github.io/iptv/categories/religious.m3u' },
        ],
      },
      {
        id: 'indexes',
        name: 'Indexes',
        flag: '📚',
        playlists: [
          { id: 'global', name: 'Global (8000+)', flag: '🌍', url: 'https://iptv-org.github.io/iptv/index.m3u' },
          { id: 'index-category', name: 'Sorted by Category', flag: '🗂️', url: 'https://iptv-org.github.io/iptv/index.category.m3u' },
          { id: 'index-country', name: 'Sorted by Country', flag: '🗺️', url: 'https://iptv-org.github.io/iptv/index.country.m3u' },
          { id: 'index-language', name: 'Sorted by Language', flag: '🗣️', url: 'https://iptv-org.github.io/iptv/index.language.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Chinese & Asian IPTV (imDazui) — Chinese regional + international channels
  // Source: https://github.com/imDazui/Tvlist-awesome-m3u-m3u8
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cn-iptv',
    name: 'China & Asia',
    description: 'Chinese regional TV + Taiwan/HK + international channels',
    flag: '🇨🇳',
    categories: [
      {
        id: 'cn-regional',
        name: 'China Regional',
        flag: '🇨🇳',
        playlists: [
          { id: 'cn-national', name: 'CCTV + 卫视', flag: '📺', url: 'https://raw.githubusercontent.com/imDazui/Tvlist-awesome-m3u-m3u8/master/m3u/国内电视台202509.m3u' },
          { id: 'cn-scenic', name: 'Scenic Cameras (114)', flag: '🏔️', url: 'https://raw.githubusercontent.com/imDazui/Tvlist-awesome-m3u-m3u8/master/m3u/全国景区源2025.m3u' },
        ],
      },
      {
        id: 'tw-hk',
        name: 'Taiwan / HK / Macau',
        flag: '🇹🇼',
        playlists: [
          { id: 'tw-hk-macau', name: 'Taiwan HK Macau (202)', flag: '🇹🇼', url: 'https://raw.githubusercontent.com/imDazui/Tvlist-awesome-m3u-m3u8/master/m3u/台湾香港澳门202506.m3u' },
        ],
      },
      {
        id: 'international',
        name: 'International (imDazui)',
        flag: '🌍',
        playlists: [
          { id: 'intl-channels', name: 'Global Channels (666)', flag: '🌍', url: 'https://raw.githubusercontent.com/imDazui/Tvlist-awesome-m3u-m3u8/master/m3u/国外电视台202409.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // YanG-1989 — Chinese Gather + Migu sports with EPG
  // Source: https://github.com/YanG-1989/m3u
  // EPG: https://material.yang-1989.xyz/epg.xml.gz (437 channels, 50K programs)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'yang-iptv',
    name: 'YanG IPTV',
    description: 'Chinese channels + Migu sports — with real EPG data',
    flag: '📡',
    categories: [
      {
        id: 'gather',
        name: 'Gather (All)',
        flag: '📡',
        playlists: [
          { id: 'gather-all', name: 'Gather (129ch + EPG)', flag: '📡', url: 'https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u' },
          { id: 'migu-sports', name: 'Migu Sports (45ch + EPG)', flag: '⚽', url: 'https://raw.githubusercontent.com/YanG-1989/m3u/main/Migu.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Auto-updated GitHub playlists — these repos run GitHub Actions on a cron
  // and commit fresh M3U files every 15min–2h. We pull them via raw URLs so
  // every "Refresh" (cache-bust) gets the latest committed version.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'auto-updated',
    name: 'Auto-Updated',
    description: 'GitHub Actions playlists — refreshed every 15min–2h automatically',
    flag: '🔄',
    categories: [
      {
        id: 'cric-sports',
        name: 'Cricket & Sports',
        flag: '🏏',
        playlists: [
          {
            id: 'crichd',
            name: 'CricHD (15min refresh)',
            flag: '🏏',
            url: 'https://raw.githubusercontent.com/abusaeeidx/CricHd-playlists-Auto-Update-permanent/main/ALL.m3u',
            count: 80,
          },
          {
            id: 't-sports',
            name: 'T-Sports BD (30min refresh)',
            flag: '📺',
            url: 'https://raw.githubusercontent.com/abusaeeidx/T-Sports-Playlist-Auto-Update/main/universal_player.m3u',
            count: 6,
          },
          {
            id: 'sm-live',
            name: 'SM Live TV (1h refresh)',
            flag: '🇧🇩',
            url: 'https://raw.githubusercontent.com/sm-monirulislam/SM-Live-TV/main/Combined_Live_TV.m3u',
            count: 50,
          },
        ],
      },
      {
        id: 'ireentv',
        name: 'IreenTV (2h refresh)',
        flag: '🛰️',
        playlists: [
          {
            id: 'toffee',
            name: 'Toffee (Bangladesh sports)',
            flag: '🇧🇩',
            url: 'https://raw.githubusercontent.com/ireentv/IreenTv-Auto-Update-Json-M3u-Playlist/main/toffee_channel_data.m3u',
            count: 60,
          },
          {
            id: 'tapmad',
            name: 'Tapmad BD',
            flag: '🇧🇩',
            url: 'https://raw.githubusercontent.com/ireentv/IreenTv-Auto-Update-Json-M3u-Playlist/main/tapmad_bd.m3u',
            count: 20,
          },
          {
            id: 'sonyliv',
            name: 'SonyLIV (India)',
            flag: '🇮🇳',
            url: 'https://raw.githubusercontent.com/ireentv/IreenTv-Auto-Update-Json-M3u-Playlist/main/sonyliv.m3u',
            count: 5,
          },
        ],
      },
      {
        id: 'india',
        name: 'India (m3u-merged sources)',
        flag: '🇮🇳',
        playlists: [
          {
            id: 'jcinema',
            name: 'JioCinema',
            flag: '🎬',
            url: 'https://raw.githubusercontent.com/alex8875/m3u/main/jcinema.m3u',
          },
          {
            id: 'jstar',
            name: 'JioStar',
            flag: '⭐',
            url: 'https://raw.githubusercontent.com/alex8875/m3u/main/jstar.m3u',
          },
          {
            id: 'jtv',
            name: 'JioTV',
            flag: '📺',
            url: 'https://raw.githubusercontent.com/alex8875/m3u/main/jtv.m3u',
          },
          {
            id: 'z5',
            name: 'Zee5',
            flag: '🎞️',
            url: 'https://raw.githubusercontent.com/alex8875/m3u/main/z5.m3u',
          },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Xtream Codes — login to any XC provider (or self-hosted kptv-proxy)
  // Enter credentials in the Admin panel. Credentials are stored in localStorage.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'xtream',
    name: 'Xtream Codes',
    description: 'Login to any XC provider — enter server + user + pass in Admin',
    flag: '🔐',
    categories: [
      {
        id: 'live',
        name: 'Live TV',
        flag: '📺',
        playlists: [
          { id: 'xc-live', name: 'Add XC account in Admin → Xtream tab', flag: '🔐', url: '/custom.m3u' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Twitch & YouTube — embed streams via official iframe players
  // Add channels in the Admin panel using twitch:NAME or youtube:ID URLs
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'embeds',
    name: 'Twitch & YouTube',
    description: 'Embed Twitch / YouTube streams via iframe — no server needed',
    flag: '🎥',
    categories: [
      {
        id: 'twitch-popular',
        name: 'Popular Twitch',
        flag: '🎮',
        playlists: [
          // These are channel-name placeholders; the player renders the iframe.
          { id: 'twitch-espn', name: 'ESPN', flag: '🏟️', url: 'twitch:espn' },
          { id: 'twitch-nfl', name: 'NFL', flag: '🏈', url: 'twitch:nfl' },
          { id: 'twitch-nba', name: 'NBA', flag: '🏀', url: 'twitch:nba' },
          { id: 'twitch-xbox', name: 'Xbox', flag: '🎮', url: 'twitch:xbox' },
          { id: 'twitch-playstation', name: 'PlayStation', flag: '🎮', url: 'twitch:playstation' },
          { id: 'twitch-riotgames', name: 'Riot Games', flag: '⚔️', url: 'twitch:riotgames' },
          { id: 'twitch-twitchpresents', name: 'Twitch Presents', flag: '🎞️', url: 'twitch:twitchpresents' },
          { id: 'twitch-twitch', name: 'Twitch', flag: '🟣', url: 'twitch:twitch' },
        ],
      },
      {
        id: 'youtube-popular',
        name: 'Popular YouTube Live',
        flag: '▶️',
        playlists: [
          // youtube-live:<channelId> — these are real 24/7 live channels
          { id: 'yt-skynews', name: 'Sky News', flag: '📰', url: 'youtube-live:UCYJDxjI3p3NxXtY9e3I2fzA' },
          { id: 'yt-abcnews', name: 'ABC News Live', flag: '📰', url: 'youtube-live:UCBi2mrWuNuyYy4gbM6fU18Q' },
          { id: 'yt-nbcnews', name: 'NBC News NOW', flag: '📰', url: 'youtube-live:UCeY0bbntWzzVIaj2z3QigXg' },
          { id: 'yt-cbsnews', name: 'CBS News', flag: '📰', url: 'youtube-live:UC8p1vwvWtl6T73JiExfWs1g' },
          { id: 'yt-aljazeera', name: 'Al Jazeera English', flag: '📰', url: 'youtube-live:UCNye-wNBqNL5ZzHSJj3l8Bg' },
          { id: 'yt-france24', name: 'France 24 English', flag: '📰', url: 'youtube-live:UCQfwfsi5VrQ8yKZ-UWmAEFg' },
          { id: 'yt-dw', name: 'DW News', flag: '📰', url: 'youtube-live:UCknLrEdhRCp1aegoMqRaCZg' },
          { id: 'yt-lofi', name: 'Lofi Girl 24/7', flag: '🎵', url: 'youtube-live:UCSJ4gkVC6NrvII8umztf0Ow' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Custom M3U Upload — paste a URL or upload a file (IPTVNator-inspired)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'custom-upload',
    name: 'Custom M3U',
    description: 'Paste a URL or upload your own M3U playlist',
    flag: '📎',
    categories: [
      {
        id: 'url',
        name: 'Load by URL',
        flag: '🔗',
        playlists: [
          { id: 'custom-url', name: 'Enter M3U URL in Admin panel', flag: '🔗', url: '/custom.m3u' },
        ],
      },
    ],
  },
]

// ─── Lookup helpers ──────────────────────────────────────────────────────────

export function getProviderById(id: string): Provider | undefined {
  return PROVIDERS.find((p) => p.id === id)
}

export function getCategoryById(providerId: string, categoryId: string): ProviderCategory | undefined {
  return getProviderById(providerId)?.categories.find((c) => c.id === categoryId)
}

export function getPlaylistById(providerId: string, categoryId: string, playlistId: string): PlaylistItem | undefined {
  return getCategoryById(providerId, categoryId)?.playlists?.find((p) => p.id === playlistId)
}

/** Resolve a provider+category+playlist path to a URL */
export function resolvePlaylistUrl(providerId: string, categoryId: string, playlistId?: string): string | undefined {
  const cat = getCategoryById(providerId, categoryId)
  if (!cat) return undefined
  if (cat.directUrl) return cat.directUrl
  if (playlistId && cat.playlists) {
    const pl = cat.playlists.find((p) => p.id === playlistId)
    return pl?.url
  }
  if (cat.playlists && cat.playlists.length > 0) return cat.playlists[0].url
  return undefined
}
