import { NextRequest, NextResponse } from 'next/server'
import { readFile } from 'fs/promises'
import path from 'path'

export const dynamic = 'force-dynamic'

// Cache the synced guide in memory
let cachedGuide: { data: any; loadedAt: number } | null = null
const CACHE_TTL = 30 * 60 * 1000 // 30 min

export async function GET(req: NextRequest) {
  const searchParams = req.nextUrl.searchParams
  const genre = searchParams.get('genre')
  const limit = parseInt(searchParams.get('limit') || '50', 10)

  // Load the synced TV guide JSON (generated by scripts/sync_tv_guide.py)
  if (!cachedGuide || Date.now() - cachedGuide.loadedAt > CACHE_TTL) {
    try {
      const guidePath = path.join(process.cwd(), 'public', 'tv-guide-sync.json')
      const content = await readFile(guidePath, 'utf-8')
      cachedGuide = { data: JSON.parse(content), loadedAt: Date.now() }
    } catch {
      // Fallback: return empty guide
      return NextResponse.json({
        genres: [],
        generatedAt: null,
        error: 'TV guide not synced yet. Run scripts/sync_tv_guide.py',
      })
    }
  }

  const guide = cachedGuide.data

  // Filter by genre if specified
  let genres = guide.genres || []
  if (genre) {
    genres = genres.filter((g: any) => g.id === genre)
  }

  // Apply limit to channels per genre
  genres = genres.map((g: any) => ({
    ...g,
    channels: (g.channels || []).slice(0, limit),
  }))

  return NextResponse.json({
    generatedAt: guide.generatedAt,
    generatedAtHuman: guide.generatedAtHuman,
    genres,
    cached: true,
  })
}
